"""Regime classification — deterministic rules only.

V4 FIX: The V2 LGB classifier was deleted because:
1. It trained on labels generated by the same rules it used as features (circular)
2. classify_regime was NOT called from features/build.py (not wired in)

The deterministic rules below are kept because they're useful as raw features
(fired directly in features/build.py via the breva_window/tivano_window flags).
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Any
from zoneinfo import ZoneInfo

from lakewind.config import load_settings

logger = logging.getLogger(__name__)

REGIMES = ["calm", "breva", "tivano", "foehn", "storm"]


@dataclass
class RegimeResult:
    regime: str
    confidence: float
    rules_detected: dict[str, bool]


def classify_regime(
    valid_time: datetime,
    feature_vector: dict[str, Any],
    *,
    use_classifier: bool = False,  # kept for API compat, ignored
) -> RegimeResult:
    """Classify weather regime using deterministic rules only.

    Priority: storm > foehn > breva > tivano > calm
    """
    s = load_settings()
    tz = ZoneInfo(s.project.timezone)
    # Treat naive UTC as UTC (consistent with solar.py fix)
    if valid_time.tzinfo is None:
        valid_time = valid_time.replace(tzinfo=ZoneInfo("UTC"))
    local_time = valid_time.astimezone(tz)
    hhmm = local_time.strftime("%H:%M")

    def _safe(v: Any) -> float | None:
        if v is None:
            return None
        try:
            return float(v)
        except (TypeError, ValueError):
            return None

    rules: dict[str, bool] = {
        "breva_window": "10:00" <= hhmm <= "18:00",
        "tivano_window": "04:00" <= hhmm <= "09:30",
        "foehn_likely": bool(feature_vector.get("foehn_likely", False)),
        "foehn_strong": bool(feature_vector.get("foehn_strong", False)),
        "high_cape": _safe(feature_vector.get("fc_icon_eu_cape")) is not None
                     and (_safe(feature_vector.get("fc_icon_eu_cape")) or 0) > 1000,
        "low_speed": _safe(feature_vector.get("fc_icon_eu_speed")) is not None
                     and (_safe(feature_vector.get("fc_icon_eu_speed")) or 999) < 3.0,
        "strong_speed": _safe(feature_vector.get("fc_icon_eu_speed")) is not None
                        and (_safe(feature_vector.get("fc_icon_eu_speed")) or 0) > 18.0,
    }

    if rules["foehn_strong"]:
        regime = "foehn"
        confidence = 0.95
    elif rules["high_cape"] and rules["strong_speed"]:
        regime = "storm"
        confidence = 0.85
    elif rules["foehn_likely"]:
        regime = "foehn"
        confidence = 0.80
    elif rules["breva_window"] and not rules["low_speed"]:
        regime = "breva"
        confidence = 0.75
    elif rules["tivano_window"] and not rules["low_speed"]:
        regime = "tivano"
        confidence = 0.75
    else:
        regime = "calm"
        confidence = 0.60

    return RegimeResult(regime=regime, confidence=confidence, rules_detected=rules)


def train_regime_classifier(*args, **kwargs) -> bool:
    """Deprecated — V4 deleted the LGB classifier (was circular/trivial)."""
    logger.warning("train_regime_classifier is deprecated in V4 (classifier deleted)")
    return False


__all__ = ["classify_regime", "RegimeResult", "REGIMES", "train_regime_classifier"]
